# Generated by Django 4.0.4 on 2022-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_img_customer_cust_img_products_product_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=300)),
                ('feedback_body', models.CharField(max_length=2000)),
                ('announced_at', models.DateField(auto_now_add=True)),
                ('update_announcement', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-update_announcement', '-announced_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
    ]
