# Generated by Django 4.0.4 on 2022-05-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_feedback_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='announced_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='update_announcement',
        ),
    ]
