# Generated by Django 4.0.4 on 2022-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='img',
            new_name='cust_img',
        ),
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
